# Generated by Django 4.1.4 on 2022-12-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField(default=1)),
                ('image', models.ImageField(default='default.jpg', upload_to='market_pics')),
                ('description', models.TextField(max_length=800)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=40)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
