# Generated by Django 4.1.4 on 2022-12-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0002_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
