# Generated by Django 4.1.4 on 2022-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0004_farm_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
