# Generated by Django 4.1.4 on 2022-12-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0005_market_slug_alter_trade_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
