# Generated by Django 4.1.4 on 2022-12-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0006_alter_farm_slug_alter_market_slug_alter_trade_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='farm',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
