# Generated by Django 4.1.4 on 2022-12-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0011_farm_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
