# Generated by Django 4.1.5 on 2023-02-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0012_alter_partner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
