# Generated by Django 4.1.7 on 2023-03-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0013_trade_scientific_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField(default=1)),
                ('image', models.ImageField(default='default.jpg', upload_to='produce_pics')),
                ('description', models.TextField(max_length=800)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=40)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Market',
        ),
    ]
