# Generated by Django 4.1.7 on 2023-03-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0014_produce_delete_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='Farm',
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact',
            field=models.CharField(max_length=200),
        ),
    ]
