# Generated by Django 4.1.7 on 2023-03-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0015_remove_trade_farm_alter_partner_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='units_left',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='units_total',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='payback_date',
        ),
    ]
