# Generated by Django 4.1.7 on 2023-03-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0016_remove_farm_crop_remove_farm_units_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='payback_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
