# Generated by Django 4.1.7 on 2023-04-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0017_trade_payback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='location',
        ),
        migrations.AddField(
            model_name='trade',
            name='partners',
            field=models.ManyToManyField(to='Asset.partner'),
        ),
    ]
