# Generated by Django 4.1.7 on 2023-04-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0018_remove_farm_location_trade_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
