# Generated by Django 4.1.7 on 2023-04-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0019_farm_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
