# Generated by Django 4.1.7 on 2023-04-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0020_produce_scientific_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='service_charge',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='service_charge',
        ),
    ]
