# Generated by Django 4.1.7 on 2023-03-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bag',
        ),
    ]
