# Generated by Django 4.1.4 on 2022-12-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='offtaker',
            name='username',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='username',
        ),
    ]
