# Generated by Django 4.1.7 on 2023-03-07 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0003_remove_farmer_username_remove_offtaker_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('other_name', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('id_card', models.CharField(choices=[('passport', 'passport'), ('voters id', 'voters id')], max_length=100)),
                ('id_num', models.CharField(max_length=200)),
                ('referral_code', models.CharField(blank=True, max_length=300, null=True)),
                ('nok', models.CharField(max_length=300)),
                ('nok_relation', models.CharField(max_length=300)),
                ('nok_contact', models.CharField(max_length=200)),
            ],
        ),
    ]
