# Generated by Django 4.1.7 on 2023-03-07 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 19, 47, 52, 297196, tzinfo=datetime.timezone.utc)),
        ),
    ]
