# Generated by Django 4.1.7 on 2023-03-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0006_alter_profile_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_num',
            new_name='id_number',
        ),
    ]
