# Generated by Django 4.1.7 on 2023-03-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0007_rename_id_num_profile_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nok',
            new_name='next_of_kin',
        ),
    ]
