# Generated by Django 4.1.7 on 2023-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0008_rename_nok_profile_next_of_kin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_card',
            field=models.CharField(choices=[('Passport', 'Passport'), ('National ID', 'National ID'), ('Driver"s  License', 'Driver"s  License')], max_length=100),
        ),
    ]
