# Generated by Django 4.1.7 on 2023-03-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0009_alter_profile_id_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='other_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
