# Generated by Django 4.1.7 on 2023-03-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0010_remove_profile_other_name_profile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='cor',
        ),
        migrations.AddField(
            model_name='profile',
            name='id_pic_back',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_pic_front',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
