# Generated by Django 4.1.7 on 2023-04-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminvoice',
            name='harvest_type',
            field=models.CharField(choices=[('cash', 'cash'), ('roll on trade', 'roll on trade'), ('crop', 'crop')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeinvoice',
            name='harvest_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Roll on trade', 'Roll on trade'), ('Crop', 'Crop')], default='Cash', max_length=50),
        ),
    ]
