# Generated by Django 4.1.4 on 2022-12-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminvoice',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradeinvoice',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
