# Generated by Django 4.1.7 on 2023-04-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_farminvoice_harvest_type_tradeinvoice_harvest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farminvoice',
            name='location',
        ),
    ]
