# Generated by Django 4.1.5 on 2023-02-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_alter_farminvoice_payment_alter_tradeinvoice_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='token',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
