# Generated by Django 4.1.7 on 2023-03-12 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transaction', '0002_tradereceipt_check_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=100, unique=True)),
                ('produce', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('units', models.PositiveIntegerField()),
                ('base_cost', models.FloatField()),
                ('service_charge', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('extra_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.CharField(blank=True, max_length=300, null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
