# Generated by Django 4.1.7 on 2023-03-12 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transaction', '0003_produceinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farminvoice',
            old_name='farm_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='farmlog',
            old_name='farm_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='produceinvoice',
            old_name='produce_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tradeinvoice',
            old_name='trade_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tradelog',
            old_name='trade_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='produceinvoice',
            name='extra_notes',
        ),
        migrations.RemoveField(
            model_name='produceinvoice',
            name='service_charge',
        ),
        migrations.CreateModel(
            name='ProduceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('produce', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('units', models.PositiveIntegerField()),
                ('base_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
