# Generated by Django 4.1.7 on 2023-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_tradeinvoice_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinvoice',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
