# Generated by Django 4.1.7 on 2023-03-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_rename_farm_name_farminvoice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminvoice',
            name='type',
            field=models.CharField(default='farm', max_length=50),
        ),
        migrations.AddField(
            model_name='tradeinvoice',
            name='type',
            field=models.CharField(default='trade', max_length=50),
        ),
    ]
