# Generated by Django 4.1.7 on 2023-04-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_remove_farminvoice_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminvoice',
            name='harvest_type',
            field=models.CharField(choices=[('Cash', 'cash'), ('Roll on trade', 'roll on trade'), ('Crop', 'crop')], max_length=50),
        ),
    ]
