# Generated by Django 4.1.7 on 2023-03-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0014_produce_delete_market'),
        ('Transaction', '0005_farminvoice_type_tradeinvoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminvoice',
            name='partner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='Asset.partner'),
        ),
        migrations.AddField(
            model_name='farmlog',
            name='partner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='Asset.partner'),
        ),
    ]
