# Generated by Django 4.1.7 on 2023-02-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_tradeinvoice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminvoice',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='farminvoice',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
