# Generated by Django 4.1.7 on 2023-04-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0006_tradeinvoice_partner_alter_farminvoice_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farminvoice',
            name='service_charge',
        ),
        migrations.RemoveField(
            model_name='tradeinvoice',
            name='service_charge',
        ),
    ]
