# Generated by Django 4.1.7 on 2023-02-27 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0006_farminvoice_image_url_farminvoice_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelog',
            name='token',
        ),
        migrations.CreateModel(
            name='TradeReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=1, max_length=300)),
                ('paylink', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.tradeinvoice')),
            ],
        ),
    ]
