# Generated by Django 4.1.7 on 2023-02-27 03:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0008_alter_tradereceipts_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=1, unique=True)),
                ('paylink', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid')], default='unpaid', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='farminvoice',
            name='farm_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='farmlog',
            name='farm_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tradeinvoice',
            name='trade_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='trade_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='TradeReceipts',
        ),
        migrations.AddField(
            model_name='tradereceipt',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.tradeinvoice'),
        ),
    ]
