# Generated by Django 4.1.7 on 2023-02-27 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0009_tradereceipt_alter_farminvoice_farm_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmlog',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='trade_name',
        ),
        migrations.AddField(
            model_name='farmlog',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Transaction.farminvoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradelog',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Transaction.tradeinvoice'),
            preserve_default=False,
        ),
    ]
