# Generated by Django 4.1.7 on 2023-02-27 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0010_remove_farmlog_farm_name_remove_tradelog_trade_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmlog',
            name='farm',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Transaction.farminvoice'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='trade',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Transaction.tradeinvoice'),
        ),
    ]
